In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
df=pd.read_csv('train.csv')

In [3]:
df.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2,random_state=2)
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [5]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

C:\Users\DELL\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

DecisionTreeClassifier()

In [6]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.9145238095238095
Accuracy of Decision Trees 0.8522619047619048

In [7]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,10)))

Logistic Regression Confusion Matrix

     0    1    2    3    4    5    6    7    8    9
0  791    0    1    0    1    9   11    1    6    1
1    0  938    2    4    0    3    0    3   12    0
2    2    9  745   16    9    4   13   13   15    3
3    1    4   19  763    0   36    5    5   20   11
4    2    5    4    0  804    1    7    3    9   21
5    9    3    4   23   10  610   15   10   34   11
6   12    4   12    1    7    8  789    0    5    1
7    3    2   13    6    4    2    0  812    2   29
8   11   12   13   18    1   21    6    6  694   11
9    3    6    2   14   25    4    0   37    7  736

In [8]:
print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,10)))

Decision Tree Confusion Matrix

     0    1    2    3    4    5    6    7    8    9
0  748    1   12    9    8   16   15    3    7    2
1    1  902   12    9   10    4    3    5   14    2
2   10   18  673   32   14    7   23   19   26    7
3   10   13   27  694    6   43    7   20   29   15
4    6    8   13    6  728   11   11    9   18   46
5   13    6   16   43    8  573   19    9   23   19
6   11    1    6    6   15   23  757    0   12    8
7    5   10   19   11    8    3    2  783    9   23
8    7   12   28   36   19   35   13    4  618   21
9    5    5    7   15   50   16    4   28   21  683

In [9]:
from sklearn.metrics import precision_score,recall_score,f1_score

In [10]:
precision_score(y_test,y_pred1,average='weighted')

0.9142150713630827

In [11]:
recall_score(y_test,y_pred1,average='weighted')

0.9145238095238095